# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "box-cutter/fedora22"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  # master
  config.vm.define 'fedoraimage', primary: true do |m|
	  m.vm.provision 'shell', path: 'provision.d/01_os.sh'
	  m.vm.provision 'shell', path: 'provision.d/10_docker.sh'
	  m.vm.provision 'shell', path: 'provision.d/20_serverspec.sh'
	  m.vm.provision 'shell', path: 'provision.d/60_demo.sh'
  end
end
