# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    # vb.gui = true
 
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end
  config.vm.define 'jessieimage', primary: true do |m|
	  m.vm.provision 'shell', path: 'provision.d/01_os.sh'
	  m.vm.provision 'shell', path: 'provision.d/10_docker.sh'
	  m.vm.provision 'shell', path: 'provision.d/20_apparmor.sh'
  end
end
